// Liste partagée des articles de stock affichés dans les modales de
// mouvement de matériel (Retrait, Ajout...).
export const ALL_STOCK_ITEMS = [
    { id: 'Souris', icon: '🖱️' },
    { id: 'Clavier', icon: '⌨️' },
    { id: 'Casque', icon: '🎧' },
    { id: 'Sacoche', icon: '💼' },
    { id: 'Sac à Dos', icon: '🎒' },
    { id: 'Chargeur', icon: '🔌' },
    { id: 'Dock', icon: '📦' },
    { id: 'Écran', icon: '🖥️' },
    { id: 'iPhone 16e', icon: '📱' },
    { id: 'iPhone 17', icon: '📱' },
    { id: 'Samsung XCOVER 7', icon: '📱' },
    { id: 'Samsung A36', icon: '📱' },
    { id: '650 G11 Neuf', icon: '💻' },
    { id: '650 G11 Occasion', icon: '💻' },
    { id: '850 G8/G10 Occasion', icon: '💻' },
    { id: 'X360 Neuf', icon: '💻' },
    { id: 'X360 Occasion', icon: '💻' },
    { id: 'Zbook Neuf', icon: '💻' },
    { id: 'Zbook Occasion', icon: '💻' },
    { id: 'Coque+Vitre iPhone 16e', icon: '🛡️' },
    { id: 'Coque+Vitre iPhone 17', icon: '🛡️' },
    { id: 'Coque+Vitre Samsung A36', icon: '🛡️' },
    { id: 'Coque Samsung XCOVER 7', icon: '🛡️' },
    { id: 'Vitre Samsung XCOVER 7', icon: '🪟' },
];
